# Generated by Django 5.2.4 on 2025-08-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='name',
            field=models.CharField(default='Untitled', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='image_url',
            field=models.CharField(max_length=500),
        ),
    ]
