# Generated by Django 5.2.4 on 2025-08-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0002_meeting_name_alter_meeting_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
