# Generated by Django 5.2.4 on 2025-08-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0003_alter_meeting_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncard',
            name='display_type',
            field=models.CharField(blank=True, choices=[('face', 'Face'), ('initial', 'Initial'), ('anonymous', 'Anonymous')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='questioncard',
            name='live',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questioncard',
            name='show_winner',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questioncard',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10),
        ),
        migrations.AlterField(
            model_name='questioncard',
            name='type',
            field=models.CharField(choices=[('slider', 'Slider'), ('short', 'Short'), ('mc', 'Multiple Choice'), ('match', 'Match'), ('rank', 'Rank'), ('ai', 'AI')], max_length=10),
        ),
    ]
