# Generated by Django 5.2.4 on 2025-08-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0004_questioncard_display_type_questioncard_live_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosegment',
            name='source_end',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='videosegment',
            name='source_start',
            field=models.FloatField(),
        ),
    ]
