# Generated by Django 5.2.4 on 2025-08-29 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0005_alter_videosegment_source_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('memory', models.TextField(blank=True, null=True)),
                ('answers', models.JSONField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bot_images/')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='authenticator.meeting')),
            ],
        ),
    ]
